// lib/generator/engine.ts
// 按设计文档 3.6 节实现的 Cursor Rules 生成引擎

import { getTemplate, getTemplatesByTags } from '../templates';
import type { GeneratorConfig } from '../templates/types';

/** 扩展变量映射（v1.1: 6 个变量） */
const VARIABLE_MAP: Record<string, (config: GeneratorConfig) => string> = {
  '{{INDENT}}': (c) => (c.style.useTabs ? '\t' : ' '.repeat(c.style.indentSize)),
  '{{QUOTE}}': (c) => (c.style.quotes === 'single' ? "'" : '"'),
  '{{SEMICOLON}}': (c) => (c.style.semicolons ? ';' : ''),
  '{{NAMING}}': (c) => c.namingConvention || c.style.namingConvention,
  '{{STRICTNESS}}': (c) => c.aiStrictness || 'moderate',
  '{{PROJECT_TYPE}}': (c) => c.projectType || 'web',
};

/**
 * 应用变量替换
 * - 先转义字面量 {{ 防止误替换
 * - 依次替换 6 个变量
 * - 恢复字面量 {{
 */
function applyVariables(content: string, config: GeneratorConfig): string {
  let result = content;
  // 先用唯一 token 转义字面量 {{，防止误替换
  result = result.replace(/\\\{\{/g, '\x00OPEN\x00');
  for (const [placeholder, resolver] of Object.entries(VARIABLE_MAP)) {
    result = result.replace(
      new RegExp(placeholder.replace(/[{}]/g, '\\$&'), 'g'),
      resolver(config)
    );
  }
  result = result.replace(/\x00OPEN\x00/g, '{{');
  return result;
}

/**
 * 生成 Header 注释
 */
function generateHeader(config: GeneratorConfig): string {
  const lines = [
    '# Cursor Rules',
    '# Generated by Cursor Rules Generator',
    `# Tech stack: ${config.selectedTags.join(', ')}`,
    '#',
  ];
  return lines.join('\n');
}

/**
 * 主生成函数
 * 按设计 3.6 节完整实现：
 * 1. 空状态防护
 * 2. 按 category 排序
 * 3. tags 过滤 + id 去重
 * 4. optional section ≥2 标签匹配
 * 5. 6 个变量替换 + 字面量 {{ 转义
 * 6. 自定义规则追加
 * 7. getTemplate 缺失 throw Error
 */
export function generateCursorRules(config: GeneratorConfig): string {
  // 1. 空状态防护
  if (!config.selectedTags || config.selectedTags.length === 0) {
    return '# Cursor Rules\n# Select a tech stack to generate your rules.\n';
  }

  const templates = getTemplatesByTags(config.selectedTags);
  const seenSectionIds = new Set<string>();
  const sections: { id: string; title: string; content: string }[] = [];

  // 2. 按 category 排序模板，保证输出顺序可预测
  const categoryOrder = ['general', 'frontend', 'backend', 'fullstack', 'mobile', 'library'];
  templates.sort((a, b) => {
    const ai = categoryOrder.indexOf(a.category);
    const bi = categoryOrder.indexOf(b.category);
    return (ai === -1 ? 99 : ai) - (bi === -1 ? 99 : bi);
  });

  // 3. 合并 + tags 过滤 + 去重
  for (const template of templates) {
    for (const section of template.sections) {
      // tags 过滤：section.tags 必须与用户选择的标签有交集
      if (section.tags && section.tags.length > 0) {
        const hasMatch = section.tags.some((tag) =>
          config.selectedTags.includes(tag)
        );
        if (!hasMatch) continue;
      }

      // 去重：同 id 的 section 只出现一次
      if (seenSectionIds.has(section.id)) continue;
      seenSectionIds.add(section.id);

      // optional section 需要至少 2 个标签匹配
      if (section.optional) {
        if (
          !section.tags ||
          section.tags.filter((t) => config.selectedTags.includes(t)).length < 2
        ) {
          continue;
        }
      }

      sections.push({
        id: section.id,
        title: section.title,
        content: applyVariables(section.content, config),
      });
    }
  }

  // 4. 组装输出：Header + 合并后的 sections + 自定义规则
  const output: string[] = [];
  output.push(generateHeader(config));

  for (const s of sections) {
    output.push(`\n## ${s.title}\n`);
    output.push(s.content);
  }

  // 5. 自定义规则 section
  if (config.customRules && config.customRules.length > 0) {
    output.push('\n## Custom Rules\n');
    for (const rule of config.customRules) {
      output.push(`### ${rule.title}`);
      output.push(rule.content);
    }
  }

  return output.join('\n');
}
